project_id = "xkfztnyodbzftlshoqui"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.formula-engine]
    verify_jwt = false
  [functions.perfumer-ai]
    verify_jwt = false
  [functions.generate-b2b-pitch]
    verify_jwt = false
  [functions.compliance-engine]
    verify_jwt = false
  [functions.assign-admin-role]
    verify_jwt = false
  [functions.convert-growth-credits]
    verify_jwt = false
  [functions.translation-agent]
    verify_jwt = false
  [functions.create-affiliate]
    verify_jwt = false
  [functions.affiliate-kit]
    verify_jwt = false
