-- ============================================================
-- The Perfume Lab — Canonical Schema
-- Core tables: client_connections + commissions
-- ============================================================
-- This file is the authoritative reference for the attribution
-- and commission tables. Migrations in supabase/migrations/ are
-- the source of truth for incremental changes; this file
-- documents the intended final schema.
-- ============================================================

-- ============================================================
-- client_connections
-- Persistent Scent-Lock attribution: one row per client email,
-- owned by the affiliate who first locked the client.
-- ============================================================
CREATE TABLE IF NOT EXISTS public.client_connections (
  id                   UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  client_email         TEXT        NOT NULL,
  original_affiliate_id UUID       REFERENCES public.affiliate_partners(id) ON DELETE SET NULL,
  acquisition_date     TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- Account classification
  account_type         TEXT        NOT NULL DEFAULT 'B2C'
                         CHECK (account_type IN ('B2C', 'B2B_Corporate')),
  -- B2B deal fields
  company_name         TEXT,
  expected_volume      TEXT,
  discount_pct         NUMERIC     DEFAULT 0
                         CHECK (discount_pct >= 0 AND discount_pct <= 40),
  -- Unique pre-negotiated checkout link token
  checkout_link_code   TEXT        UNIQUE
                         DEFAULT substr(replace(gen_random_uuid()::text, '-', ''), 1, 16),
  -- Order stats (denormalised for fast reads)
  last_order_at        TIMESTAMPTZ,
  total_orders         INTEGER     NOT NULL DEFAULT 0,
  total_spent          NUMERIC     NOT NULL DEFAULT 0,
  notes                TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (client_email)
);

-- ============================================================
-- commissions
-- Immutable ledger of every commission event generated by the
-- Scent-Lock auto-attribution trigger and smart-commission
-- edge function.  One row per commission event (direct or
-- Tier 2 override).
-- ============================================================
CREATE TABLE IF NOT EXISTS public.commissions (
  id                UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  -- The affiliate who earns this commission
  affiliate_id      UUID        NOT NULL REFERENCES public.affiliate_partners(id) ON DELETE CASCADE,
  -- Source: the order that triggered the commission
  order_id          UUID        REFERENCES public.orders(id) ON DELETE SET NULL,
  -- Optional: the direct affiliate (when this row is a Tier-2 override)
  source_affiliate_id UUID      REFERENCES public.affiliate_partners(id) ON DELETE SET NULL,
  -- Classification
  account_type      TEXT        NOT NULL DEFAULT 'B2C'
                      CHECK (account_type IN ('B2C', 'B2B_Corporate')),
  commission_tier   INTEGER     NOT NULL DEFAULT 1
                      CHECK (commission_tier IN (1, 2)),
  -- Financials
  order_amount      NUMERIC     NOT NULL DEFAULT 0,
  commission_pct    NUMERIC     NOT NULL DEFAULT 0,
  commission_amount NUMERIC     NOT NULL DEFAULT 0,
  -- Lifecycle
  status            TEXT        NOT NULL DEFAULT 'pending'
                      CHECK (status IN ('pending', 'approved', 'paid', 'cancelled')),
  approved_at       TIMESTAMPTZ,
  paid_at           TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- Row-Level Security
-- ============================================================
ALTER TABLE public.client_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.commissions         ENABLE ROW LEVEL SECURITY;

-- client_connections policies (idempotent — use CREATE POLICY IF NOT EXISTS
-- once Supabase supports it; for now duplicates are safe to skip).

-- commissions: affiliates see only their own rows; admins see all
CREATE POLICY "Affiliates read own commissions"
  ON public.commissions FOR SELECT TO authenticated
  USING (
    affiliate_id IN (
      SELECT id FROM public.affiliate_partners WHERE user_id = auth.uid()
    )
    OR has_role(auth.uid(), 'admin')
    OR is_super_admin(auth.uid())
  );

CREATE POLICY "System inserts commissions"
  ON public.commissions FOR INSERT TO authenticated
  WITH CHECK (
    has_role(auth.uid(), 'admin') OR is_super_admin(auth.uid())
  );

CREATE POLICY "Admins update commissions"
  ON public.commissions FOR UPDATE TO authenticated
  USING (has_role(auth.uid(), 'admin') OR is_super_admin(auth.uid()))
  WITH CHECK (has_role(auth.uid(), 'admin') OR is_super_admin(auth.uid()));

-- ============================================================
-- Triggers
-- ============================================================
CREATE TRIGGER update_client_connections_updated_at
  BEFORE UPDATE ON public.client_connections
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_commissions_updated_at
  BEFORE UPDATE ON public.commissions
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ============================================================
-- Auto-Attribution Trigger (handle_new_order)
-- Fires AFTER INSERT on orders; matches customer_email to
-- client_connections and forcibly assigns affiliate regardless
-- of session metadata.
-- See: migrations/20260310132823_*.sql for full implementation.
-- ============================================================
