import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401, headers: corsHeaders });
    }

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    // Verify JWT
    const token = authHeader.replace("Bearer ", "");
    const { data: { user }, error: authError } = await supabase.auth.getUser(token);
    if (authError || !user) {
      return new Response(JSON.stringify({ error: "Invalid token" }), { status: 401, headers: corsHeaders });
    }

    const body = await req.json();
    const { name, email, instagram, tiktok, youtube, country, experience } = body;

    if (!name?.trim() || !email?.trim()) {
      return new Response(JSON.stringify({ error: "Name and email are required" }), { status: 400, headers: corsHeaders });
    }

    // Check if user already has an affiliate account
    const { data: existing } = await supabase
      .from("affiliate_partners")
      .select("id, slug")
      .eq("user_id", user.id)
      .maybeSingle();

    if (existing) {
      return new Response(JSON.stringify({ affiliate: existing, alreadyExists: true }), { headers: corsHeaders });
    }

    // Insert affiliate (slug is auto-generated by trigger)
    const socialHandles = [instagram, tiktok, youtube].filter(Boolean).join(", ").slice(0, 200) || null;
    const { data, error } = await supabase
      .from("affiliate_partners")
      .insert({
        user_id: user.id,
        display_name: name.trim().slice(0, 200),
        email: email.trim().slice(0, 255),
        company_name: socialHandles,
        social_links: { instagram: instagram || null, tiktok: tiktok || null, youtube: youtube || null },
      })
      .select("id, slug, referral_code, display_name, points")
      .single();

    if (error) throw error;

    // Award initial signup points
    await supabase.from("affiliate_point_events").insert({
      affiliate_id: data.id,
      user_id: user.id,
      action: "signup",
      points: 25,
      metadata: { country, experience },
    });

    // Update points
    await supabase
      .from("affiliate_partners")
      .update({ points: 25 })
      .eq("id", data.id);

    return new Response(JSON.stringify({ affiliate: { ...data, points: 25 }, alreadyExists: false }), { headers: corsHeaders });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "Internal error";
    return new Response(JSON.stringify({ error: message }), { status: 500, headers: corsHeaders });
  }
});
